---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: invalid-local-policy
spec:
  path: ./conftest/invalid/invalid-local-policy
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: invalid-parent-policy
spec:
  path: ./conftest/invalid/invalid-parent-policy
